[package]
name = "frr-agent"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.36", features = ["std", "derive", "usage"]}
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-test = { version = "0.2.5" }

