name: build.yml

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: lab
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Build project
        run: cargo build

      - name: Run tests
        run: cargo test

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Check code formatting
        run: cargo fmt -- --check
